#! /usr/bin/bash

if [ -z "$1" ]
  then
    exit
fi

echo -e "testerfile = open('$1', 'r')\ncontent = testerfile.read()\ntesterfile.close()\nlines = content.splitlines()\n" > $1.py
touch $1
code $1 $1.py